# Generated by Django 3.2.2 on 2024-04-02 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('favorite', models.CharField(default='', max_length=120, verbose_name='Favorite')),
                ('cart', models.PositiveIntegerField(default=0, verbose_name='cart')),
                ('wished_qty', models.PositiveIntegerField(default=0, verbose_name='cart')),
                ('bought_qty', models.PositiveIntegerField(default=0, verbose_name='cart')),
                ('comic', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='e_commerce.comic', verbose_name='Comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
