FROM python:3.9.5
ENV PYTHONUNBUFFERED=1
# Corremos este comando para actualizar pip.
RUN python -m pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt
# En este caso como ya está creado el proyecto asignamos
# como directorio de trabajo el directorio raíz del mismo.
WORKDIR /opt/back_end/marvel 
#cuando se levanta el directorio se va a la ruta especificada en WORKDIR
COPY . /opt/back_end
#Copio todo el directorio de donde esta parado a la ruta especificada en COPY
RUN apt-get update && apt-get -y install vim
#Ejecuto un comando especificado en RUN
CMD python manage.py runserver 0.0.0.0:8000
#Ejecutar un comando de consola en CMD en el caso de CMD solo se puede ejecutar una sola vez tambien es pisada por la directiva COMMAND del .yml